import React from "react";
import "./App.css";
import Search from "./Search";
import Display from "./Display";
import Top from "./Top";
import Modal from "./Modal";

class App extends React.Component {
  constructor(props) {
    super(props);

    this.doSearch = this.doSearch.bind(this);
    this.updateDisplay = this.updateDisplay.bind(this);
    this.seedValues = this.seedValues.bind(this);
    this.doRandom = this.doRandom.bind(this);
    this.toggleModal = this.toggleModal.bind(this);
    this.toggleModalOff = this.toggleModalOff.bind(this);

    this.seedValues();
  }

  // generate ordered random values
  doRandom(number, range) {
    var retArr = [];
    for (let i = 0; i < range; i++) {
      retArr.push(i);
    }
    while (retArr.length > number) {
      var r = Math.floor(Math.random() * retArr.length);
      retArr.splice(r, 1);
    }
    return retArr;
  }

  // startup pick target country and catagories
  seedValues() {
    // Select target country
    const targetCountry = data[Math.floor(Math.random() * data.length)];

    // Select which 4 catagories
    const seeds = this.doRandom(4, Object.keys(catagoryNames).length);

    //generate inital state values
    const initialState = {};
    for (let i in seeds) {
      var key = Object.keys(catagoryNames)[seeds[i]];
      initialState[key] = {
        target: targetCountry[key],
        high: "",
        highName: "\u00A0",
        low: "",
        lowName: "\u00A0",
      };
    }

    //set initial state
    this.state = {
      catagories: initialState,
      history: [],
      showModal: true,
      modalType: "how",
    };
  }

  // help, win, settings

  updateDisplay(data) {
    console.log(
      "updateDisplay",
      data.name,
      data.pop,
      data.area,
      data.density,
      data.gdp,
      data.gdpcapita
    );

    const newState = {}; //we fill this instead of repeatedly calling state

    //history stores what gets inputed, and changed
    const history = this.state.history;
    const turnData = []; //this will be added to history

    //loop through data catagories; name, pop, area,
    for (const key in data) {
      //ignore name column (ignoring name row)
      if (this.state.catagories[key]) {
        const catagory = this.state.catagories[key];
        const rank = data[key];

        newState[key] = {
          target: catagory.target,
          high: "",
          highName: "",
          low: "",
          lowName: "",
        }; //adding new blank row

        if (rank < catagory.target) {
          //1: higher rank
          if (catagory.high === "" || rank > catagory.high) {
            newState[key].high = rank;
            newState[key].highName = data.name;
            turnData.push("🔼");
          } else {
            newState[key].high = catagory.high;
            newState[key].highName = catagory.highName;
            turnData.push("⏫");
          }
          newState[key].low = catagory.low;
          newState[key].lowName = catagory.lowName;
        } else if (rank > catagory.target) {
          //2: lower rank
          if (catagory.low === "" || rank < catagory.low) {
            newState[key].low = rank;
            newState[key].lowName = data.name;
            turnData.push("🔽");
          } else {
            newState[key].low = catagory.low;
            newState[key].lowName = catagory.lowName;
            turnData.push("⏬");
          }
          newState[key].high = catagory.high;
          newState[key].highName = catagory.highName;
        } else {
          console.log("win condition");
          newState[key].low = rank;
          newState[key].lowName = data.name;
          newState[key].high = rank;
          newState[key].highName = data.name;
          turnData.push("☑️");
          this.toggleModal("win");
        }
      }
    }

    // Update State
    this.setState({
      catagories: newState,
      history: history.concat([{ country: data.name, values: turnData }]),
    });
  }

  doSearch(searchTerm) {
    for (let v in data) {
      if (data[v].name.toLowerCase() === searchTerm.toLowerCase()) {
        this.updateDisplay(data[v]);
        return;
      }
    }
  }

  toggleModal(type) {
    console.log("the culprit");
    const modalValue = !this.state.showModal;
    this.setState({
      showModal: modalValue,
      modalType: type,
    });
  }

  toggleModalOff() {
    const modalValue = !this.state.showModal;
    this.setState({
      showModal: modalValue,
    });
  }

  render() {
    return (
      <div>
        {this.state.showModal ? (
          <Modal
            toggleModalOff={this.toggleModalOff}
            modalType={this.state.modalType}
            // refactor this
            history={this.state.history}
          />
        ) : null}
        <Top
          guessCount={this.state.history.length}
          toggleModal={this.toggleModal}
        />
        <Display
          values={this.state.catagories}
          currentCountry={
            this.state.history.length
              ? this.state.history[this.state.history.length - 1].country
              : ""
          }
        />
        <Search doSearch={this.doSearch} />
      </div>
    );
  }
}

const catagoryNames = {
  alpha: "Alphabetically",
  area: "Area",
  density: "Density",
  gdp: "GDP",
  gdpcapita: "GDP Per Capita",
  pop: "Population",
};

const data = [
  {
    name: "Afghanistan",
    alpha: 1,
    pop: 37,
    area: 40,
    density: 122,
    gdp: 112,
    gdpcapita: 184,
  },
  {
    name: "Albania",
    alpha: 2,
    pop: 138,
    area: 142,
    density: 83,
    gdp: 126,
    gdpcapita: 105,
  },
  {
    name: "Algeria",
    alpha: 3,
    pop: 33,
    area: 10,
    density: 166,
    gdp: 53,
    gdpcapita: 115,
  },
  {
    name: "Andorra",
    alpha: 4,
    pop: 185,
    area: 179,
    density: 56,
    gdp: 162,
    gdpcapita: 24,
  },
  {
    name: "Angola",
    alpha: 5,
    pop: 44,
    area: 22,
    density: 153,
    gdp: 57,
    gdpcapita: 117,
  },
  {
    name: "Antigua and Barbuda",
    alpha: 6,
    pop: 184,
    area: 182,
    density: 47,
    gdp: 175,
    gdpcapita: 51,
  },
  {
    name: "Argentina",
    alpha: 7,
    pop: 32,
    area: 8,
    density: 171,
    gdp: 21,
    gdpcapita: 56,
  },
  {
    name: "Armenia",
    alpha: 8,
    pop: 135,
    area: 137,
    density: 84,
    gdp: 133,
    gdpcapita: 112,
  },
  {
    name: "Australia",
    alpha: 9,
    pop: 55,
    area: 6,
    density: 191,
    gdp: 13,
    gdpcapita: 13,
  },
  {
    name: "Austria",
    alpha: 10,
    pop: 96,
    area: 114,
    density: 79,
    gdp: 27,
    gdpcapita: 16,
  },
  {
    name: "Azerbaijan",
    alpha: 11,
    pop: 89,
    area: 113,
    density: 69,
    gdp: 86,
    gdpcapita: 110,
  },
  {
    name: "Bahamas",
    alpha: 12,
    pop: 172,
    area: 161,
    density: 142,
    gdp: 131,
    gdpcapita: 29,
  },
  {
    name: "Bahrain",
    alpha: 13,
    pop: 149,
    area: 173,
    density: 3,
    gdp: 95,
    gdpcapita: 37,
  },
  {
    name: "Bangladesh",
    alpha: 14,
    pop: 8,
    area: 94,
    density: 6,
    gdp: 42,
    gdpcapita: 148,
  },
  {
    name: "Barbados",
    alpha: 15,
    pop: 175,
    area: 183,
    density: 9,
    gdp: 155,
    gdpcapita: 46,
  },
  {
    name: "Belarus",
    alpha: 16,
    pop: 95,
    area: 82,
    density: 135,
    gdp: 79,
    gdpcapita: 91,
  },
  {
    name: "Belgium",
    alpha: 17,
    pop: 80,
    area: 136,
    density: 23,
    gdp: 24,
    gdpcapita: 20,
  },
  {
    name: "Belize",
    alpha: 18,
    pop: 171,
    area: 147,
    density: 173,
    gdp: 170,
    gdpcapita: 103,
  },
  {
    name: "Benin",
    alpha: 19,
    pop: 76,
    area: 98,
    density: 80,
    gdp: 139,
    gdpcapita: 168,
  },
  {
    name: "Bhutan",
    alpha: 20,
    pop: 161,
    area: 132,
    density: 164,
    gdp: 167,
    gdpcapita: 123,
  },
  {
    name: "Bolivia",
    alpha: 21,
    pop: 79,
    area: 26,
    density: 180,
    gdp: 93,
    gdpcapita: 124,
  },
  {
    name: "Bosnia and Herzegovina",
    alpha: 22,
    pop: 133,
    area: 126,
    density: 121,
    gdp: 113,
    gdpcapita: 95,
  },
  {
    name: "Botswana",
    alpha: 23,
    pop: 142,
    area: 47,
    density: 188,
    gdp: 114,
    gdpcapita: 80,
  },
  {
    name: "Brazil",
    alpha: 24,
    pop: 6,
    area: 5,
    density: 155,
    gdp: 8,
    gdpcapita: 68,
  },
  {
    name: "Brunei",
    alpha: 25,
    pop: 170,
    area: 164,
    density: 104,
    gdp: 132,
    gdpcapita: 34,
  },
  {
    name: "Bulgaria",
    alpha: 26,
    pop: 105,
    area: 100,
    density: 120,
    gdp: 75,
    gdpcapita: 77,
  },
  {
    name: "Burkina Faso",
    alpha: 27,
    pop: 58,
    area: 73,
    density: 107,
    gdp: 129,
    gdpcapita: 180,
  },
  {
    name: "Burundi",
    alpha: 28,
    pop: 77,
    area: 143,
    density: 19,
    gdp: 161,
    gdpcapita: 193,
  },
  {
    name: "Cabo Verde",
    alpha: 29,
    pop: 166,
    area: 166,
    density: 63,
    gdp: 171,
    gdpcapita: 125,
  },
  {
    name: "Cambodia",
    alpha: 30,
    pop: 70,
    area: 88,
    density: 92,
    gdp: 106,
    gdpcapita: 155,
  },
  {
    name: "Cameroon",
    alpha: 31,
    pop: 52,
    area: 52,
    density: 126,
    gdp: 96,
    gdpcapita: 156,
  },
  {
    name: "Canada",
    alpha: 32,
    pop: 39,
    area: 4,
    density: 186,
    gdp: 10,
    gdpcapita: 19,
  },
  {
    name: "Central African Republic",
    alpha: 33,
    pop: 123,
    area: 42,
    density: 183,
    gdp: 168,
    gdpcapita: 189,
  },
  {
    name: "Chad",
    alpha: 34,
    pop: 71,
    area: 21,
    density: 178,
    gdp: 138,
    gdpcapita: 179,
  },
  {
    name: "Chile",
    alpha: 35,
    pop: 62,
    area: 37,
    density: 154,
    gdp: 40,
    gdpcapita: 53,
  },
  {
    name: "China",
    alpha: 36,
    pop: 1,
    area: 2,
    density: 57,
    gdp: 2,
    gdpcapita: 76,
  },
  {
    name: "Colombia",
    alpha: 37,
    pop: 29,
    area: 25,
    density: 137,
    gdp: 37,
    gdpcapita: 88,
  },
  {
    name: "Comoros",
    alpha: 38,
    pop: 159,
    area: 170,
    density: 17,
    gdp: 181,
    gdpcapita: 159,
  },
  {
    name: "Costa Rica",
    alpha: 39,
    pop: 120,
    area: 125,
    density: 88,
    gdp: 76,
    gdpcapita: 61,
  },
  {
    name: "Croatia",
    alpha: 40,
    pop: 128,
    area: 123,
    density: 110,
    gdp: 78,
    gdpcapita: 59,
  },
  {
    name: "Cuba",
    alpha: 41,
    pop: 82,
    area: 102,
    density: 82,
    gdp: 63,
    gdpcapita: 75,
  },
  {
    name: "Cyprus",
    alpha: 42,
    pop: 155,
    area: 162,
    density: 67,
    gdp: 108,
    gdpcapita: 43,
  },
  {
    name: "Czechia",
    alpha: 43,
    pop: 85,
    area: 115,
    density: 62,
    gdp: 47,
    gdpcapita: 38,
  },
  {
    name: "Democratic Republic of the Congo",
    alpha: 44,
    pop: 16,
    area: 11,
    density: 140,
    gdp: 92,
    gdpcapita: 186,
  },
  {
    name: "Denmark",
    alpha: 45,
    pop: 113,
    area: 129,
    density: 66,
    gdp: 34,
    gdpcapita: 10,
  },
  {
    name: "Djibouti",
    alpha: 46,
    pop: 157,
    area: 146,
    density: 139,
    gdp: 165,
    gdpcapita: 130,
  },
  {
    name: "Dominica",
    alpha: 47,
    pop: 186,
    area: 174,
    density: 90,
    gdp: 186,
    gdpcapita: 83,
  },
  {
    name: "Dominican Republic",
    alpha: 48,
    pop: 84,
    area: 127,
    density: 46,
    gdp: 68,
    gdpcapita: 82,
  },
  {
    name: "Ecuador",
    alpha: 49,
    pop: 66,
    area: 76,
    density: 112,
    gdp: 62,
    gdpcapita: 89,
  },
  {
    name: "Egypt",
    alpha: 50,
    pop: 14,
    area: 29,
    density: 85,
    gdp: 44,
    gdpcapita: 135,
  },
  {
    name: "El Salvador",
    alpha: 51,
    pop: 110,
    area: 149,
    density: 30,
    gdp: 103,
    gdpcapita: 113,
  },
  {
    name: "Equatorial Guinea",
    alpha: 52,
    pop: 150,
    area: 139,
    density: 131,
    gdp: 130,
    gdpcapita: 72,
  },
  {
    name: "Eritrea",
    alpha: 53,
    pop: 131,
    area: 103,
    density: 146,
    gdp: 169,
    gdpcapita: 183,
  },
  {
    name: "Estonia",
    alpha: 54,
    pop: 152,
    area: 130,
    density: 150,
    gdp: 99,
    gdpcapita: 39,
  },
  {
    name: "Eswatini",
    alpha: 55,
    pop: 156,
    area: 153,
    density: 118,
    gdp: 156,
    gdpcapita: 114,
  },
  {
    name: "Ethiopia",
    alpha: 56,
    pop: 12,
    area: 28,
    density: 73,
    gdp: 66,
    gdpcapita: 173,
  },
  {
    name: "Fiji",
    alpha: 57,
    pop: 158,
    area: 151,
    density: 133,
    gdp: 150,
    gdpcapita: 92,
  },
  {
    name: "Finland",
    alpha: 58,
    pop: 114,
    area: 70,
    density: 169,
    gdp: 41,
    gdpcapita: 17,
  },
  {
    name: "France",
    alpha: 59,
    pop: 22,
    area: 48,
    density: 71,
    gdp: 7,
    gdpcapita: 23,
  },
  {
    name: "Gabon",
    alpha: 60,
    pop: 143,
    area: 75,
    density: 182,
    gdp: 120,
    gdpcapita: 84,
  },
  {
    name: "Gambia",
    alpha: 61,
    pop: 141,
    area: 160,
    density: 41,
    gdp: 177,
    gdpcapita: 177,
  },
  {
    name: "Georgia",
    alpha: 62,
    pop: 130,
    area: 118,
    density: 124,
    gdp: 119,
    gdpcapita: 116,
  },
  {
    name: "Germany",
    alpha: 63,
    pop: 19,
    area: 63,
    density: 39,
    gdp: 4,
    gdpcapita: 18,
  },
  {
    name: "Ghana",
    alpha: 64,
    pop: 47,
    area: 81,
    density: 65,
    gdp: 74,
    gdpcapita: 142,
  },
  {
    name: "Greece",
    alpha: 65,
    pop: 86,
    area: 95,
    density: 105,
    gdp: 51,
    gdpcapita: 41,
  },
  {
    name: "Grenada",
    alpha: 66,
    pop: 180,
    area: 185,
    density: 27,
    gdp: 180,
    gdpcapita: 66,
  },
  {
    name: "Guatemala",
    alpha: 67,
    pop: 65,
    area: 101,
    density: 55,
    gdp: 69,
    gdpcapita: 107,
  },
  {
    name: "Guinea",
    alpha: 68,
    pop: 74,
    area: 77,
    density: 128,
    gdp: 137,
    gdpcapita: 167,
  },
  {
    name: "Guinea-Bissau",
    alpha: 69,
    pop: 147,
    area: 138,
    density: 114,
    gdp: 178,
    gdpcapita: 174,
  },
  {
    name: "Guyana",
    alpha: 70,
    pop: 160,
    area: 84,
    density: 189,
    gdp: 158,
    gdpcapita: 104,
  },
  {
    name: "Haiti",
    alpha: 71,
    pop: 81,
    area: 141,
    density: 20,
    gdp: 142,
    gdpcapita: 171,
  },
  {
    name: "Honduras",
    alpha: 72,
    pop: 91,
    area: 99,
    density: 96,
    gdp: 105,
    gdpcapita: 133,
  },
  {
    name: "Hungary",
    alpha: 73,
    pop: 93,
    area: 109,
    density: 81,
    gdp: 56,
    gdpcapita: 54,
  },
  {
    name: "Iceland",
    alpha: 74,
    pop: 173,
    area: 104,
    density: 193,
    gdp: 104,
    gdpcapita: 6,
  },
  {
    name: "India",
    alpha: 75,
    pop: 2,
    area: 7,
    density: 18,
    gdp: 5,
    gdpcapita: 141,
  },
  {
    name: "Indonesia",
    alpha: 76,
    pop: 4,
    area: 14,
    density: 59,
    gdp: 16,
    gdpcapita: 118,
  },
  {
    name: "Iran",
    alpha: 77,
    pop: 18,
    area: 17,
    density: 130,
    gdp: 26,
    gdpcapita: 97,
  },
  {
    name: "Iraq",
    alpha: 78,
    pop: 36,
    area: 56,
    density: 95,
    gdp: 52,
    gdpcapita: 101,
  },
  {
    name: "Ireland",
    alpha: 79,
    pop: 122,
    area: 119,
    density: 111,
    gdp: 33,
    gdpcapita: 7,
  },
  {
    name: "Israel",
    alpha: 80,
    pop: 99,
    area: 148,
    density: 21,
    gdp: 31,
    gdpcapita: 22,
  },
  {
    name: "Italy",
    alpha: 81,
    pop: 23,
    area: 72,
    density: 51,
    gdp: 9,
    gdpcapita: 28,
  },
  {
    name: "Ivory Coast",
    alpha: 82,
    pop: 53,
    area: 66,
    density: 102,
    gdp: 94,
    gdpcapita: 152,
  },
  {
    name: "Jamaica",
    alpha: 83,
    pop: 136,
    area: 158,
    density: 35,
    gdp: 121,
    gdpcapita: 100,
  },
  {
    name: "Japan",
    alpha: 84,
    pop: 11,
    area: 62,
    density: 25,
    gdp: 3,
    gdpcapita: 27,
  },
  {
    name: "Jordan",
    alpha: 85,
    pop: 87,
    area: 110,
    density: 74,
    gdp: 87,
    gdpcapita: 111,
  },
  {
    name: "Kazakhstan",
    alpha: 86,
    pop: 63,
    area: 9,
    density: 184,
    gdp: 55,
    gdpcapita: 74,
  },
  {
    name: "Kenya",
    alpha: 87,
    pop: 27,
    area: 46,
    density: 93,
    gdp: 67,
    gdpcapita: 151,
  },
  {
    name: "Kiribati",
    alpha: 88,
    pop: 179,
    area: 172,
    density: 60,
    gdp: 192,
    gdpcapita: 147,
  },
  {
    name: "Kuwait",
    alpha: 89,
    pop: 127,
    area: 152,
    density: 40,
    gdp: 58,
    gdpcapita: 32,
  },
  {
    name: "Kyrgyzstan",
    alpha: 90,
    pop: 109,
    area: 86,
    density: 147,
    gdp: 145,
    gdpcapita: 161,
  },
  {
    name: "Laos",
    alpha: 91,
    pop: 103,
    area: 79,
    density: 149,
    gdp: 117,
    gdpcapita: 134,
  },
  {
    name: "Latvia",
    alpha: 92,
    pop: 148,
    area: 122,
    density: 151,
    gdp: 98,
    gdpcapita: 48,
  },
  {
    name: "Lebanon",
    alpha: 93,
    pop: 107,
    area: 159,
    density: 10,
    gdp: 80,
    gdpcapita: 78,
  },
  {
    name: "Lesotho",
    alpha: 94,
    pop: 144,
    area: 135,
    density: 113,
    gdp: 166,
    gdpcapita: 160,
  },
  {
    name: "Liberia",
    alpha: 95,
    pop: 121,
    area: 106,
    density: 129,
    gdp: 160,
    gdpcapita: 176,
  },
  {
    name: "Libya",
    alpha: 96,
    pop: 106,
    area: 16,
    density: 187,
    gdp: 90,
    gdpcapita: 94,
  },
  {
    name: "Liechtenstein",
    alpha: 97,
    pop: 190,
    area: 190,
    density: 42,
    gdp: 147,
    gdpcapita: 1,
  },
  {
    name: "Lithuania",
    alpha: 98,
    pop: 139,
    area: 121,
    density: 138,
    gdp: 84,
    gdpcapita: 45,
  },
  {
    name: "Luxembourg",
    alpha: 99,
    pop: 164,
    area: 168,
    density: 38,
    gdp: 72,
    gdpcapita: 3,
  },
  {
    name: "Madagascar",
    alpha: 100,
    pop: 51,
    area: 44,
    density: 134,
    gdp: 134,
    gdpcapita: 187,
  },
  {
    name: "Malawi",
    alpha: 101,
    pop: 61,
    area: 107,
    density: 54,
    gdp: 149,
    gdpcapita: 191,
  },
  {
    name: "Malaysia",
    alpha: 102,
    pop: 45,
    area: 65,
    density: 89,
    gdp: 36,
    gdpcapita: 67,
  },
  {
    name: "Maldives",
    alpha: 103,
    pop: 168,
    area: 187,
    density: 4,
    gdp: 152,
    gdpcapita: 70,
  },
  {
    name: "Mali",
    alpha: 104,
    pop: 59,
    area: 23,
    density: 172,
    gdp: 118,
    gdpcapita: 169,
  },
  {
    name: "Malta",
    alpha: 105,
    pop: 169,
    area: 186,
    density: 5,
    gdp: 128,
    gdpcapita: 31,
  },
  {
    name: "Marshall Islands",
    alpha: 106,
    pop: 187,
    area: 189,
    density: 28,
    gdp: 191,
    gdpcapita: 120,
  },
  {
    name: "Mauritania",
    alpha: 107,
    pop: 125,
    area: 27,
    density: 185,
    gdp: 151,
    gdpcapita: 162,
  },
  {
    name: "Mauritius",
    alpha: 108,
    pop: 154,
    area: 169,
    density: 11,
    gdp: 124,
    gdpcapita: 64,
  },
  {
    name: "Mexico",
    alpha: 109,
    pop: 10,
    area: 13,
    density: 119,
    gdp: 15,
    gdpcapita: 71,
  },
  {
    name: "Micronesia",
    alpha: 110,
    pop: 167,
    area: 177,
    density: 8,
    gdp: 189,
    gdpcapita: 178,
  },
  {
    name: "Moldova",
    alpha: 111,
    pop: 129,
    area: 134,
    density: 70,
    gdp: 143,
    gdpcapita: 140,
  },
  {
    name: "Monaco",
    alpha: 112,
    pop: 189,
    area: 194,
    density: 1,
    gdp: 148,
    gdpcapita: 2,
  },
  {
    name: "Mongolia",
    alpha: 113,
    pop: 134,
    area: 18,
    density: 194,
    gdp: 135,
    gdpcapita: 119,
  },
  {
    name: "Montenegro",
    alpha: 114,
    pop: 163,
    area: 155,
    density: 136,
    gdp: 153,
    gdpcapita: 79,
  },
  {
    name: "Morocco",
    alpha: 115,
    pop: 40,
    area: 55,
    density: 101,
    gdp: 61,
    gdpcapita: 126,
  },
  {
    name: "Mozambique",
    alpha: 116,
    pop: 46,
    area: 34,
    density: 141,
    gdp: 127,
    gdpcapita: 188,
  },
  {
    name: "Myanmar",
    alpha: 117,
    pop: 26,
    area: 39,
    density: 100,
    gdp: 71,
    gdpcapita: 158,
  },
  {
    name: "Namibia",
    alpha: 118,
    pop: 140,
    area: 33,
    density: 192,
    gdp: 125,
    gdpcapita: 98,
  },
  {
    name: "Nauru",
    alpha: 119,
    pop: 194,
    area: 193,
    density: 13,
    gdp: 193,
    gdpcapita: 60,
  },
  {
    name: "Nepal",
    alpha: 120,
    pop: 49,
    area: 92,
    density: 53,
    gdp: 102,
    gdpcapita: 166,
  },
  {
    name: "Netherlands",
    alpha: 121,
    pop: 68,
    area: 133,
    density: 16,
    gdp: 18,
    gdpcapita: 14,
  },
  {
    name: "New Zealand",
    alpha: 122,
    pop: 124,
    area: 74,
    density: 170,
    gdp: 50,
    gdpcapita: 21,
  },
  {
    name: "Nicaragua",
    alpha: 123,
    pop: 108,
    area: 97,
    density: 127,
    gdp: 123,
    gdpcapita: 139,
  },
  {
    name: "Niger",
    alpha: 124,
    pop: 56,
    area: 20,
    density: 165,
    gdp: 144,
    gdpcapita: 190,
  },
  {
    name: "Nigeria",
    alpha: 125,
    pop: 7,
    area: 30,
    density: 45,
    gdp: 30,
    gdpcapita: 144,
  },
  {
    name: "North Korea",
    alpha: 126,
    pop: 54,
    area: 96,
    density: 49,
    gdp: 115,
    gdpcapita: 175,
  },
  {
    name: "North Macedonia",
    alpha: 127,
    pop: 145,
    area: 144,
    density: 103,
    gdp: 136,
    gdpcapita: 96,
  },
  {
    name: "Norway",
    alpha: 128,
    pop: 117,
    area: 61,
    density: 177,
    gdp: 28,
    gdpcapita: 5,
  },
  {
    name: "Oman",
    alpha: 129,
    pop: 118,
    area: 68,
    density: 176,
    gdp: 70,
    gdpcapita: 58,
  },
  {
    name: "Pakistan",
    alpha: 130,
    pop: 5,
    area: 35,
    density: 32,
    gdp: 39,
    gdpcapita: 154,
  },
  {
    name: "Palau",
    alpha: 131,
    pop: 192,
    area: 181,
    density: 143,
    gdp: 190,
    gdpcapita: 49,
  },
  {
    name: "Palestine",
    alpha: 132,
    pop: 119,
    area: 163,
    density: 7,
    gdp: 122,
    gdpcapita: 128,
  },
  {
    name: "Panama",
    alpha: 133,
    pop: 126,
    area: 116,
    density: 123,
    gdp: 73,
    gdpcapita: 55,
  },
  {
    name: "Papua New Guinea",
    alpha: 134,
    pop: 97,
    area: 54,
    density: 162,
    gdp: 111,
    gdpcapita: 137,
  },
  {
    name: "Paraguay",
    alpha: 135,
    pop: 104,
    area: 59,
    density: 168,
    gdp: 89,
    gdpcapita: 93,
  },
  {
    name: "Peru",
    alpha: 136,
    pop: 43,
    area: 19,
    density: 152,
    gdp: 49,
    gdpcapita: 86,
  },
  {
    name: "Philippines",
    alpha: 137,
    pop: 13,
    area: 71,
    density: 24,
    gdp: 38,
    gdpcapita: 127,
  },
  {
    name: "Poland",
    alpha: 138,
    pop: 38,
    area: 69,
    density: 68,
    gdp: 23,
    gdpcapita: 57,
  },
  {
    name: "Portugal",
    alpha: 139,
    pop: 88,
    area: 108,
    density: 76,
    gdp: 46,
    gdpcapita: 36,
  },
  {
    name: "Qatar",
    alpha: 140,
    pop: 137,
    area: 157,
    density: 37,
    gdp: 54,
    gdpcapita: 9,
  },
  {
    name: "Republic of the Congo",
    alpha: 141,
    pop: 115,
    area: 64,
    density: 175,
    gdp: 141,
    gdpcapita: 146,
  },
  {
    name: "Romania",
    alpha: 142,
    pop: 60,
    area: 80,
    density: 99,
    gdp: 48,
    gdpcapita: 62,
  },
  {
    name: "Russia",
    alpha: 143,
    pop: 9,
    area: 1,
    density: 181,
    gdp: 11,
    gdpcapita: 63,
  },
  {
    name: "Rwanda",
    alpha: 144,
    pop: 75,
    area: 145,
    density: 15,
    gdp: 140,
    gdpcapita: 172,
  },
  {
    name: "Saint Kitts and Nevis",
    alpha: 145,
    pop: 188,
    area: 188,
    density: 52,
    gdp: 182,
    gdpcapita: 42,
  },
  {
    name: "Saint Lucia",
    alpha: 146,
    pop: 178,
    area: 178,
    density: 31,
    gdp: 172,
    gdpcapita: 69,
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha: 147,
    pop: 181,
    area: 184,
    density: 33,
    gdp: 185,
    gdpcapita: 81,
  },
  {
    name: "Samoa",
    alpha: 148,
    pop: 177,
    area: 167,
    density: 115,
    gdp: 184,
    gdpcapita: 106,
  },
  {
    name: "San Marino",
    alpha: 149,
    pop: 191,
    area: 191,
    density: 12,
    gdp: 173,
    gdpcapita: 15,
  },
  {
    name: "Sao Tome and Principe",
    alpha: 150,
    pop: 176,
    area: 171,
    density: 44,
    gdp: 188,
    gdpcapita: 145,
  },
  {
    name: "Saudi Arabia",
    alpha: 151,
    pop: 41,
    area: 12,
    density: 174,
    gdp: 19,
    gdpcapita: 40,
  },
  {
    name: "Senegal",
    alpha: 152,
    pop: 69,
    area: 85,
    density: 98,
    gdp: 110,
    gdpcapita: 157,
  },
  {
    name: "Serbia",
    alpha: 153,
    pop: 98,
    area: 111,
    density: 87,
    gdp: 85,
    gdpcapita: 102,
  },
  {
    name: "Seychelles",
    alpha: 154,
    pop: 183,
    area: 180,
    density: 50,
    gdp: 176,
    gdpcapita: 52,
  },
  {
    name: "Sierra Leone",
    alpha: 155,
    pop: 102,
    area: 117,
    density: 77,
    gdp: 157,
    gdpcapita: 185,
  },
  {
    name: "Singapore",
    alpha: 156,
    pop: 112,
    area: 176,
    density: 2,
    gdp: 35,
    gdpcapita: 11,
  },
  {
    name: "Slovakia",
    alpha: 157,
    pop: 116,
    area: 128,
    density: 75,
    gdp: 64,
    gdpcapita: 44,
  },
  {
    name: "Slovenia",
    alpha: 158,
    pop: 146,
    area: 150,
    density: 86,
    gdp: 83,
    gdpcapita: 35,
  },
  {
    name: "Solomon Islands",
    alpha: 159,
    pop: 162,
    area: 140,
    density: 160,
    gdp: 179,
    gdpcapita: 143,
  },
  {
    name: "Somalia",
    alpha: 160,
    pop: 72,
    area: 41,
    density: 158,
    gdp: 174,
    gdpcapita: 194,
  },
  {
    name: "South Africa",
    alpha: 161,
    pop: 25,
    area: 24,
    density: 132,
    gdp: 32,
    gdpcapita: 90,
  },
  {
    name: "South Korea",
    alpha: 162,
    pop: 28,
    area: 105,
    density: 14,
    gdp: 12,
    gdpcapita: 30,
  },
  {
    name: "South Sudan",
    alpha: 163,
    pop: 83,
    area: 43,
    density: 167,
    gdp: 159,
    gdpcapita: 192,
  },
  {
    name: "Spain",
    alpha: 164,
    pop: 30,
    area: 51,
    density: 94,
    gdp: 14,
    gdpcapita: 33,
  },
  {
    name: "Sri Lanka",
    alpha: 165,
    pop: 57,
    area: 120,
    density: 26,
    gdp: 65,
    gdpcapita: 108,
  },
  {
    name: "Sudan",
    alpha: 166,
    pop: 34,
    area: 15,
    density: 156,
    gdp: 59,
    gdpcapita: 131,
  },
  {
    name: "Suriname",
    alpha: 167,
    pop: 165,
    area: 90,
    density: 190,
    gdp: 163,
    gdpcapita: 99,
  },
  {
    name: "Sweden",
    alpha: 168,
    pop: 90,
    area: 58,
    density: 159,
    gdp: 22,
    gdpcapita: 12,
  },
  {
    name: "Switzerland",
    alpha: 169,
    pop: 100,
    area: 131,
    density: 48,
    gdp: 20,
    gdpcapita: 4,
  },
  {
    name: "Syria",
    alpha: 170,
    pop: 67,
    area: 87,
    density: 91,
    gdp: 116,
    gdpcapita: 164,
  },
  {
    name: "Tajikistan",
    alpha: 171,
    pop: 94,
    area: 93,
    density: 116,
    gdp: 146,
    gdpcapita: 170,
  },
  {
    name: "Tanzania",
    alpha: 172,
    pop: 24,
    area: 31,
    density: 117,
    gdp: 81,
    gdpcapita: 165,
  },
  {
    name: "Thailand",
    alpha: 173,
    pop: 20,
    area: 50,
    density: 64,
    gdp: 25,
    gdpcapita: 85,
  },
  {
    name: "Timor-Leste",
    alpha: 174,
    pop: 153,
    area: 154,
    density: 97,
    gdp: 164,
    gdpcapita: 138,
  },
  {
    name: "Togo",
    alpha: 175,
    pop: 101,
    area: 124,
    density: 58,
    gdp: 154,
    gdpcapita: 181,
  },
  {
    name: "Tonga",
    alpha: 176,
    pop: 182,
    area: 175,
    density: 61,
    gdp: 187,
    gdpcapita: 109,
  },
  {
    name: "Trinidad and Tobago",
    alpha: 177,
    pop: 151,
    area: 165,
    density: 36,
    gdp: 107,
    gdpcapita: 50,
  },
  {
    name: "Tunisia",
    alpha: 178,
    pop: 78,
    area: 91,
    density: 108,
    gdp: 88,
    gdpcapita: 121,
  },
  {
    name: "Turkey",
    alpha: 179,
    pop: 17,
    area: 36,
    density: 78,
    gdp: 17,
    gdpcapita: 65,
  },
  {
    name: "Turkmenistan",
    alpha: 180,
    pop: 111,
    area: 53,
    density: 179,
    gdp: 91,
    gdpcapita: 87,
  },
  {
    name: "Tuvalu",
    alpha: 181,
    pop: 193,
    area: 192,
    density: 22,
    gdp: 194,
    gdpcapita: 122,
  },
  {
    name: "Uganda",
    alpha: 182,
    pop: 31,
    area: 83,
    density: 43,
    gdp: 100,
    gdpcapita: 182,
  },
  {
    name: "Ukraine",
    alpha: 183,
    pop: 35,
    area: 45,
    density: 109,
    gdp: 60,
    gdpcapita: 132,
  },
  {
    name: "United Arab Emirates",
    alpha: 184,
    pop: 92,
    area: 112,
    density: 72,
    gdp: 29,
    gdpcapita: 26,
  },
  {
    name: "United Kingdom",
    alpha: 185,
    pop: 21,
    area: 78,
    density: 34,
    gdp: 6,
    gdpcapita: 25,
  },
  {
    name: "United States of America",
    alpha: 186,
    pop: 3,
    area: 3,
    density: 145,
    gdp: 1,
    gdpcapita: 8,
  },
  {
    name: "Uruguay",
    alpha: 187,
    pop: 132,
    area: 89,
    density: 163,
    gdp: 77,
    gdpcapita: 47,
  },
  {
    name: "Uzbekistan",
    alpha: 188,
    pop: 42,
    area: 57,
    density: 106,
    gdp: 82,
    gdpcapita: 149,
  },
  {
    name: "Vanuatu",
    alpha: 189,
    pop: 174,
    area: 156,
    density: 161,
    gdp: 183,
    gdpcapita: 129,
  },
  {
    name: "Venezuela",
    alpha: 190,
    pop: 50,
    area: 32,
    density: 148,
    gdp: 43,
    gdpcapita: 73,
  },
  {
    name: "Vietnam",
    alpha: 191,
    pop: 15,
    area: 67,
    density: 29,
    gdp: 45,
    gdpcapita: 136,
  },
  {
    name: "Yemen",
    alpha: 192,
    pop: 48,
    area: 49,
    density: 125,
    gdp: 97,
    gdpcapita: 163,
  },
  {
    name: "Zambia",
    alpha: 193,
    pop: 64,
    area: 38,
    density: 157,
    gdp: 101,
    gdpcapita: 153,
  },
  {
    name: "Zimbabwe",
    alpha: 194,
    pop: 73,
    area: 60,
    density: 144,
    gdp: 109,
    gdpcapita: 150,
  },
];

export default App;
